### ISSUE TITLE
Watch Attribute Changes

### ISSUE THREAD

**Issue by gflohr** [Corion/Filesys-Notify-Win32-ReadDirectoryChanges#2]
Is there a particular reason that the module does not watch attribute changes? If not, I think it would make sense to add it since `Linux::Inotify2`, `Mac::FSEvents`, and `IO::KQueue` all seem to support that feature.

**Comment by Corion** [comment]
Yeah - I don't know why I skipped that one - I'll look at adding that to the watch mask.

**Comment by gflohr** [comment]
Cool, thanks!

**Comment by Corion** [comment]
This should be addressed by 56af473e0c1fc3a46e8969d37da93522a07b6862 , now released as 0.05 onto CPAN
