### ISSUE TITLE
Feature Request: Document Buffer Size (and make it configurable)

### ISSUE THREAD

**Issue by gflohr** [Corion/Filesys-Notify-Win32-ReadDirectoryChanges#3]
Hi, again!

you use a buffer size of 65500 bytes for the returned file system information but this limit is not documented. And wouldn't it be an improvement to make the buffer size configurable (think `rm -rf node_modules` ;))

Also, the action 'unknown' is not documented. That action is actually returned, if the buffer size is too small.

I can create a PR if you want to but I must admit that I'm not experienced at all with Win32::API stuff.

**Comment by Corion** [comment]
Released as 0.06

**Comment by gflohr** [comment]
Thanks! :)
