### ISSUE TITLE
Logic for "rename" Action not Perfect

### ISSUE THREAD

**Issue by gflohr** [Corion/Filesys-Notify-Win32-ReadDirectoryChanges#4]
In your logic for creating the extra "rename" event, when you get a "new_name", you just check that the last action was "old_name" but that could have been triggered for a different file. Maybe that case can never occur but it would be safer to also compare the paths.

**Comment by Corion** [comment]
No - comparing the paths won't help if you're moving a file from `foo/bar.txt` to `baz/batman.jpg` . Yes, the Windows API could generate the events separately but that's something we have to live with.

**Comment by gflohr** [comment]
Yes, of course, that's true. My bad.
